## old static inventory approach & im going to switch to dynamic inventory approach using terraform and ansible inventory plugin
---
- name: Configure Jenkins Server
  hosts: jenkins
  become: yes

  roles:
    - java
    - jenkins
    - docker
    - trivycd