---
- name: Install dependencies
  apt:
    name:
      - wget
      - gnupg
      - lsb-release
      - ca-certificates
    state: present
    update_cache: yes

- name: Ensure keyring directory exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download Trivy key
  get_url:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    dest: /tmp/trivy.key
    mode: '0644'

- name: Convert Trivy key
  command: gpg --dearmor -o /usr/share/keyrings/trivy.gpg /tmp/trivy.key

- name: Add Trivy repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main"
    state: present
    filename: trivy
    update_cache: yes

- name: Install Trivy
  apt:
    name: trivy
    state: present